[project]
name = "pipeline-and-peril"
version = "0.1.0"
description = "A board game teaching distributed systems concepts through RPG dice mechanics"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "ruff>=0.1.0",
]
